/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-dim": "#4caaef",
        "error-dim": "#d73357",
        "on-background": "#ffffff",
        "error-container": "#a70138",
        "surface": "#0e0e0e",
        "on-primary-fixed-variant": "#003d5f",
        "on-secondary-container": "#f8c2ff",
        "on-error": "#490013",
        "tertiary-fixed-dim": "#5bef90",
        "primary-container": "#49a8ec",
        "surface-variant": "#262626",
        "secondary": "#e67aff",
        "outline-variant": "#484847",
        "surface-container": "#1a1a1a",
        "tertiary-dim": "#5bef90",
        "on-surface-variant": "#adaaaa",
        "on-tertiary-fixed": "#004a23",
        "tertiary-container": "#6bfe9c",
        "surface-bright": "#2c2c2c",
        "tertiary-fixed": "#6bfe9c",
        "background": "#0e0e0e",
        "on-error-container": "#ffb2b9",
        "surface-tint": "#5cb8fd",
        "secondary-container": "#7c0599",
        "inverse-primary": "#006498",
        "primary-fixed-dim": "#4caaef",
        "on-primary": "#003351",
        "inverse-on-surface": "#565555",
        "secondary-fixed-dim": "#f2aaff",
        "on-tertiary-fixed-variant": "#006a35",
        "secondary-dim": "#dd72f7",
        "on-tertiary-container": "#005f2f",
        "on-primary-fixed": "#001a2c",
        "on-primary-container": "#00253c",
        "on-secondary": "#47005a",
        "surface-container-low": "#131313",
        "on-secondary-fixed-variant": "#8417a1",
        "secondary-fixed": "#f7beff",
        "inverse-surface": "#fcf9f8",
        "surface-container-high": "#20201f",
        "on-tertiary": "#006834",
        "surface-container-highest": "#262626",
        "tertiary": "#c3ffcd",
        "primary-fixed": "#5cb8fd",
        "primary": "#5cb8fd",
        "on-surface": "#ffffff",
        "surface-dim": "#0e0e0e",
        "surface-container-lowest": "#000000",
        "error": "#ff6e84",
        "outline": "#767575",
        "on-secondary-fixed": "#5b0072"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Be Vietnam Pro", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
};